export const FETCH_ALL_USERS_PENDING = "FETCH_ALL_USERS_PENDING";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS_FAILED";

export const ADD_USER_PENDING = "ADD_USER_PENDING";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILED = "ADD_USER_FAILED";

export const REMOVE_USER_PENDING = "REMOVE_USER_PENDING";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_FAILED = "REMOVE_USER_FAILED";

export const EDIT_USER_PENDING = "EDIT_USER_PENDING";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

export const SELECT_USER_PENDING = "SELECT_USER_PENDING";
export const SELECT_USER_SUCCESS = "SELECT_USER_SUCCESS";
export const SELECT_USER_FAILED = "SELECT_USER_FAILED";

export const BASE_URL = `http://localhost:8000/customers`;
