export const FETCH_ALL_VIDEOS_PENDING = "FETCH_ALL_VIDEOS_PENDING";
export const FETCH_ALL_VIDEOS_SUCCESS = "FETCH_ALL_VIDEOS_SUCCESS";
export const FETCH_ALL_VIDEOS_FAILED = "FETCH_ALL_VIDEOS_FAILED";

export const ADD_VIDEO_PENDING = "ADD_VIDEO_PENDING";
export const ADD_VIDEO_SUCCESS = "ADD_VIDEO_SUCCESS";
export const ADD_VIDEO_FAILED = "ADD_VIDEO_FAILED";

export const REMOVE_VIDEO_PENDING = "REMOVE_VIDEO_PENDING";
export const REMOVE_VIDEO_SUCCESS = "REMOVE_VIDEO_SUCCESS";
export const REMOVE_VIDEO_FAILED = "REMOVE_VIDEO_FAILED";

export const EDIT_VIDEO_PENDING = "EDIT_VIDEO_PENDING";
export const EDIT_VIDEO_SUCCESS = "EDIT_VIDEO_SUCCESS";
export const EDIT_VIDEO_FAILED = "EDIT_VIDEO_FAILED";

export const SELECT_VIDEO_PENDING = "SELECT_VIDEO_PENDING";
export const SELECT_VIDEO_SUCCESS = "SELECT_VIDEO_SUCCESS";
export const SELECT_VIDEO_FAILED = "SELECT_VIDEO_FAILED";

export const BASE_URL = `http://localhost:8000/videos`;
